export function generateProjectConfig(): string {
  return JSON.stringify(
    {
      miniprogramRoot: 'dist/',
      projectname: 'forgestudio-taro-project',
      description: 'Generated by ForgeStudio',
      appid: 'touristappid',
      setting: {
        urlCheck: true,
        es6: false,
        enhance: false,
        compileHotReLoad: false,
        postcss: false,
        minified: false,
      },
      compileType: 'miniprogram',
    },
    null,
    2,
  )
}
